telegram_bot_token: "5737744110:AAHWNw3rnHF_uodIdoqNff-erSdk-evE" #change it
maintenance: false #turn it to true to force the bot to go into maintanance mode.
generate_one_for_each: true
db_path: "db/database.db"
max_users: 3000
traffic_limit: 15516192768 #14 GB
outline_ip: "101.125.27.39"
cloudflare:
  auth_key: "4b622221384a372e2c23f5e323a6e25"
  zone_id: "d0d07812312467c16821370123182827c"
  auth_email: "womanlifefreedom@gmail.com"
  prefix_subdomain_name: "cdir-"
  domain: "wlfvip.com"
  ip: "25.129.222.125"